maximum:
  name: 50
  content: 140
  description: 1000
  address: 255
  email: 255
  phone: 20
per_user: 10
per_category: 5
per_order: 5
counter_default: 1
minimum:
  pass: 6
sessions:
  is_remember: "1"
slide:
  previous: "Previous"
  next: "Next"
product:
  default: "default"
  see_detail: "See detail!"
top_order: 5
admin_user_perpage: 10
size:
  product_detail: "500x400"
category_roof: 0
product_recent: 8
product_perpage: 12
